models:
  - name: "gpt-4"
    type: "api"           # Indica que será acessado via API
    provider: "OpenAI"    # Fornecedor do modelo
    api_key: "your_api_key_here"
    parameters:
      temperature: 0.7
      max_tokens: 1500
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0

  - name: "llama-2"
    type: "local"         # Indica que será carregado localmente
    model_path: "/path/to/llama-2-model"  # Caminho para o modelo local
    parameters:
      temperature: 0.7
      max_tokens: 1500
      top_p: 0.9
      frequency_penalty: 0.0
      presence_penalty: 0.0

  - name: "bloom"
    type: "api"
    provider: "HuggingFace"   # Fornecedor do modelo
    api_key: "huggingface_api_key"
    parameters:
      temperature: 0.9
      max_tokens: 1000
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
